sudo: required
services:
- docker
before_install:
- docker build -t backpack812/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run backpack812/react-test npm run test -- --coverage --watchAll=false
after_success:
- docker build -t backpack812/multi-client ./client
- docker build -t backpack812/multi-nginx ./nginx
- docker build -t backpack812/multi-server ./server
- docker build -t backpack812/multi-worker ./worker
- docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
- docker push backpack812/multi-client
- docker push backpack812/multi-nginx
- docker push backpack812/multi-server
- docker push backpack812/multi-worker
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  app: complex-docker
  env: Complexdocker-env
  bucket_name: elasticbeanstalk-us-east-2-674034146380
  on:
    branch: main
